public enum TokenType {
    INT, FLOAT, STRING, BOOL,
    IF, ELSE, WHILE,
    FUNCION, RETURN,
    READ, WRITE,
    TRUE, FALSE,
    AND, OR, NOT,
    ID, NUMENTERO, NUMDECIMAL, CADENASTRING,
    SUMA, RESTA, MULTI, DIV,
    MAYORQ, MENORQ, MAYORIGU, MENORIGU, EQUIVA, NEGA,
    IGUAL,
    PARENI, PAREND, COMA, DOSP, PUNCOM,
    NEWLINE, INDENT, DEDENT, EOF
}